# docker-compose.yml

services:
  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=${NODE_ENV}
    volumes:
      - ./frontend:/app
